version: '3.8'

services:
  backend:
    build:
      context: .
      target: backend
    image: onlyoffice/pipedrive-docspace-backend:${PRODUCT_VERSION}
    depends_on:
      - postgres
      - redis
    environment:
      - BASE_URL=${BACKEND_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/${POSTGRES_DB}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_USERNAME=${REDIS_USERNAME}
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD}
      - SPRING_DATA_REDIS_DATABASE=${REDIS_DB}
      - PIPEDRIVE_CLIENT_ID=${PIPEDRIVE_CLIENT_ID}
      - PIPEDRIVE_CLIENT_SECRET=${PIPEDRIVE_CLIENT_SECRET}
    stdin_open: true
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      target: frontend
      args:
        - BACKEND_URL=${BACKEND_URL}
    image: onlyoffice/pipedrive-docspace-frontend:${PRODUCT_VERSION}
    stdin_open: true
    ports:
      - "3000:80"

  postgres:
    image: postgres:16.2
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    stdin_open: true
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0.12
    stdin_open: true
    ports:
      - "6379:6379"