name: Build docspace-pipedrive

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Specify tag (ex. 1.0.0)'
        type: string
        required: true
      repo:
        description: Choose repo
        required: true
        default: test
        type: choice
        options:
        - test
        - dockerhub
  
      
jobs:
  prepare-build:
    name: "Prepare build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ (inputs.repo == 'test') && secrets.DOCKER_TEST_REGISTRY || 'docker.io' }}
          username: ${{ (inputs.repo == 'test') && secrets.DOCKER_TEST_USERNAME || secrets.DOCKER_HUB_USERNAME }}
          password: ${{ (inputs.repo == 'test') && secrets.DOCKER_TEST_ACCESS_TOKEN || secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: build
        
